### ISSUE TITLE
What check is pre-commit and what check is for CI pipeline?

### ISSUE THREAD

**Issue by deusebio** [CGnal/python-ci-template#10]
I believe one item worth discussing and agreeing at this stage is what goes into pre-commit and what gets automatically run in CI pipelines

To be honest, since personally I commit lots of WIPs, I would try to keep pre-commit as light as possible, deferring to CI pipelines all checks that may be heavy or annoying during WIPs. Beside, I believe that the "compliant" checks (mypy, linting) should be included ANYWAY in CI pipelines. Pre-commit is something that one could also disable and technically I suspect that nothing prevents not-compliant code to be pushed to the remote repository and merged. We need a central, standard and centralize check procedure to assess whether things are fine... 

Having said this, my personal opinion is that tests, mypy (given that WIPs most likely won't pass static checks) and linting would be best suited to a CI pipeline, rather than pre-commits.

**Comment by NicolaDonelli** [comment]
I agree that there should be a difference, in particular, because some checks are time expensive and a bit cumbersome to fix.
Following this logic I'd go for:
*pre-commit checks* (using pre-commit): 
- Style enforcing and code formatting: Flake and/or Black
- Requirements update: Update requirements and requirements_dev if corresponding *.in file had been changed

*pull-request checks* (using github's workflows):
- pre-commit checks
- Tests (unit and integration): pytest
- Type consistency: mypy
- Docstrings: TBD

Special consideration about type consistency checking with mypy: although I believe it would be much more user friendly to execute this locally before opening a PR, so maybe it could be the case to implement a bash script to run this at need, this could be quite long to run for large codebases so I decided to put it to execute only at PR time.

Finally, I think it could be useful to search for a tool that at least could check for docstings' presence (if not even compile automatically some basic docstrings).

**Comment by deusebio** [comment]
As agreed, we will leave to the pre-commit only the requirements. All the rest (mypy, linting and tests) will be deferred to the CI Pipeline. 

We need to introduce a block to "merge-request" or "pull-request" to be merged, if checks do not pass

**Comment by NicolaDonelli** [comment]
> As agreed, we will leave to the pre-commit only the requirements. All the rest (mypy, linting and tests) will be deferred to the CI Pipeline.
> 
> We need to introduce a block to "merge-request" or "pull-request" to be merged, if checks do not pass

Wouldn't it be even better to stop the PR from being opened if checks are not passed?
I am not sure if this would be possible but I am afraid that simply returning the failed check and maybe blocking the possibility to merge could lead to eternal PRs in the case in which the Reviewer does not review the PR because checks are failed and the Author does not solve problems since he didn't pay attention to failed checks... 
We have already been there with our repos and I am afraid that this situation could only get worse when we open our source to external contributions.
