### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by deusebio** [CGnal/python-ci-template#12]
I know that we have just recently closed a PR about putting in a bin folder for running tests, linting, etc, but it would be very cool to rather replace these scripts with a Makefile. I used to use Makefile a bit in my previous life in academia (I did make everything, even latex papers) and it can be quite convenient and handy.

**Comment by NicolaDonelli** [comment]
I know almost nothing about makefiles, could you please give me some more detail on how they work and how they could be useful in our context?

Any reference will be very welcome!

**Comment by deusebio** [comment]
There you go! https://makefiletutorial.com/

You can custom several procedure, wrapping them using the make command. In the terminal you can just type:

make tests => run unittests
make linting => perform linting
make mypy => perform static typing checks
make dist => to create the tar.gz
make release => to create the tar.gz and upload to the pypi
make clean => to remove cache file (pyc and clean distribution)
make docs => to create the documentation using sphinx (actually I believe we are already using makefile in the docs, where we type make html or make pdf for creating the docs)

**Comment by NicolaDonelli** [comment]
So basically it is a collection of shortcuts to specific commands.
I like it.

Maybe we could list here some ideas and then open a PR implementing them.
Extending the one you already proposed I'd add:

- reqs => compile requirements
- tests => run unittests (is this really useful since all test are launched simply with the `pytest` command)?
- lint => perform linting
- mypy => perform static typing checks, with predefined flags
- dist => to create the tar.gz
- release => to create the tar.gz and upload to the pypi
- clean => to remove cache file (pyc and clean distribution)
- docs => to create the documentation using sphinx (actually I believe we are already using makefile in the docs, where we type make html or make pdf for creating the docs)
- setup => install requirements
- setup_dev => install requiremets_dev
- install => install (updated) package

**Comment by afalcioni** [comment]
Note for the project setup: since in issue #11 we decided to move the pre-commit config file to a folder other than root (i.e. `confs/.pre-commit-config.yaml`),  when that issue will be closed the correct pre-commit install command will be as follows:
`pre-commit install --config=confs/.pre-commit-config.yaml`

In addition, it would be useful to create a shortcut for the pre-commit run command as well: 
`pre-commit run --config=confs/.pre-commit-config.yaml --all-files`

@deusebio

**Comment by deusebio** [comment]
Should we have a keyword "pre_commit_setup" for performing the command you attached?

**Comment by NicolaDonelli** [comment]
Nope. 
Since it is a "once in a lifetime" setup, I'd put it in the same "initialization" command as the process described in issue #6 by @ascartabelli

**Comment by deusebio** [comment]
Honestly, I don't mind. If one wants to change the pre-commit and install a new version of pre-commit hooks it can be useful. Beside, at the moment, I'm not using any pre-commit command in the Makefile. 

It is really small efforts to add this shortcut and, by the way (now that you mention this), we could also have a command to run the "first" initial steps (first step create the setup.cfg and then setup the pre-commit)

**Comment by NicolaDonelli** [comment]
Actually, I cannot see why one would want to install pre-commit after initial configuration and, in any case, I wouldn't make it easy since it wouldn't be something a user should do.
On the other hand, I agree that there should be a "run-pre-commit" command executing `pre-commit run --config=confs/.pre-commit-config.yaml --all-files`, to run pre-commit locally (added now to my previous list)

**Comment by deusebio** [comment]
Given yesterday discussion, pre-commit is something where we are not really enforcing strict policies, but rather guidelines and that is somewhat developer dependent. We don't mind what developers prefer to have in their pre-commits, given that we have a CI pipeline in place that ensure to be compliant with standards. I'm ok if (given your workflow process) you want to re-install a pre-commit with more thorough checks
