### ISSUE TITLE
Move to Python 3.7 (at least)

### ISSUE THREAD

**Issue by MattiaPedro** [CGnal/python-ci-template#27]
Atm the whole package requires 3.6 which is out of standard since ages.

At the moment using python 3.7 raises an error with requirements since pip cannot find dataclasses==0.8 cause dataclasses is builtin since 3.7.

Immediate pro: apparently solves the compatibility issue in requirements for importlib-metadata between flask and sphinx since installing flask with 3.7 gives you importlib-metadata==4.8.3.

@deusebio @NicolaDonelli

**Comment by deusebio** [comment]
Yes, I've experiencing the same thing. We can probably first get everything stable (linting, mypy, etc) and then increase the python version. But yes, I totally agree, we should move away from 3.6, or rather make things a bit more orthogonal between versions (changing python version also means to change requirements, since some packages are not supported on e.g. python3.6 after a certain version)

**Comment by NicolaDonelli** [comment]
Probably moving to Python 3.7 could solve the problems with requirements...

**Comment by deusebio** [comment]
I have just tested out to setup the repo from scratch by also removing the requirements.txt and requirements_ci.txt (old requirements_dev.txt), letting the "make reqs" (or any other make command actually, since basically everything depends on these requirements) create them and using them for tests, static typing checks and etc. 

No issue is raised, also with Python3.7

*IMPORTANT POINT*
I'm starting to think that it would probably be a cleaner template to also avoid specifying in the template hard requirements.txt and requirements_ci.txt, and rather let pip-tools create them the first time we run make, after the repo is created. This also allow to create always at the beginning environments which are up to date with the latest versions of the packages
